// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUbDq0Y-skcfDAU3Y_nTAakkErdMLPzw',
    appId: '1:992615527698:web:8f631650ae06cdb15defcb',
    messagingSenderId: '992615527698',
    projectId: 'chat-app-85ffd',
    authDomain: 'chat-app-85ffd.firebaseapp.com',
    storageBucket: 'chat-app-85ffd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuAXPdqJQrkFiM3CtCUPWYfLQcx_0MKQ',
    appId: '1:992615527698:android:0430644107ab69515defcb',
    messagingSenderId: '992615527698',
    projectId: 'chat-app-85ffd',
    storageBucket: 'chat-app-85ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKQLsSydPbA8BOBAHmBsA59WFQEESw8w',
    appId: '1:992615527698:ios:0a0b1bd30666425e5defcb',
    messagingSenderId: '992615527698',
    projectId: 'chat-app-85ffd',
    storageBucket: 'chat-app-85ffd.appspot.com',
    androidClientId: '992615527698-61c04ue8s7g3231gq2sta5rvgn025a9h.apps.googleusercontent.com',
    iosClientId: '992615527698-27783pgndc9d377s2ursblr14iqr57f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKQLsSydPbA8BOBAHmBsA59WFQEESw8w',
    appId: '1:992615527698:ios:0a0b1bd30666425e5defcb',
    messagingSenderId: '992615527698',
    projectId: 'chat-app-85ffd',
    storageBucket: 'chat-app-85ffd.appspot.com',
    androidClientId: '992615527698-61c04ue8s7g3231gq2sta5rvgn025a9h.apps.googleusercontent.com',
    iosClientId: '992615527698-27783pgndc9d377s2ursblr14iqr57f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
